import Head from "next/head";

export default function SignPostPage() {

  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex h-screen justify-center">
       <div>Profile view</div>
      </main>
    </>
  );
}